Gary/add login prompt
TeamLunaris/easypoints-integration-boilerplate pull request #18
Opened 2022-09-06 08:14 UTC by Gazwai

- Added a Login prompt snippet which can be rendered when the user is not logged in

2022-09-07 02:26 UTC, NexPB requested changes

2022-09-07 02:26 UTC, NexPB commented on snippets/easy_points_login_prompt.liquid
> +      <small class="ep-disabled-text">ポイントのご利用には<a href="/account/login">ログイン</a>していただく必要がございます。</small>
- For routing use https://shopify.dev/api/liquid/objects#routes
- Text should be translated. But translations have to be added in the app when we insert our main assets.

2022-09-07 02:26 UTC, NexPB commented on assets/easy_points_integration.css
> +  opacity: 0.7;
Maybe we should just use `text-decoration: underline;`

2022-09-07 02:26 UTC, NexPB commented on snippets/easy_points_login_prompt.liquid
> +    {%- unless customer -%}
Double unless blocks use `and`

2022-09-08 05:41 UTC, Gazwai commented on assets/easy_points_integration.css
> +  opacity: 0.7;
Changed to underline

2022-09-08 05:42 UTC, Gazwai commented on snippets/easy_points_login_prompt.liquid
> +    {%- unless customer -%}
Used  ```or``` for the the double unless

2022-09-08 05:43 UTC, Gazwai commented on snippets/easy_points_login_prompt.liquid
> +      <small class="ep-disabled-text">ポイントのご利用には<a href="/account/login">ログイン</a>していただく必要がございます。</small>
I changed the routing to use the liquid routes

2022-09-09 08:57 UTC, Gazwai commented
Tested on dev theme with ja.json directly manipulated

<img width="464" alt="Screen Shot 2022-09-09 at 17 55 12" src="https://user-images.githubusercontent.com/84076465/189312510-ef0e02f4-928d-42c8-95c5-240ff345aba5.png">
<img width="428" alt="Screen Shot 2022-09-09 at 17 55 16" src="https://user-images.githubusercontent.com/84076465/189312512-ab4fcde1-eb19-44a5-98dd-9f2e35bab5bb.png">

2022-09-12 04:22 UTC, NexPB requested changes

2022-09-12 04:22 UTC, NexPB commented on snippets/easy_points_login_prompt.liquid
> +    class="ep-disabled-text"
I don't like the naming of this css class here, it's not _disabled_.

2022-09-12 07:08 UTC, Gazwai commented on snippets/easy_points_login_prompt.liquid
> +    class="ep-disabled-text"
Very true, I'll modify that

2022-09-12 23:13 UTC, NexPB approved these changes

2022-09-12 23:13 UTC, merged