Gary/set coupon on redeem
TeamLunaris/easypoints-integration-boilerplate pull request #20
Opened 2022-09-13 02:27 UTC by Gazwai

- Setting coupon on the redeem btn instead of the submit btn
- Should now be the default for all integrations

2022-09-15 01:44 UTC, NexPB requested changes

2022-09-15 01:44 UTC, NexPB commented on assets/easy_points_integration.js
> +  },
Why... are we programmatically clicking a button? What's wrong with the standard `reset`.

2022-09-15 01:44 UTC, NexPB commented on assets/easy_points_integration.css
> +
We can just set the `opacity` and `cursor`

2022-09-15 01:44 UTC, NexPB commented on assets/easy_points_integration.js
> +      sessionStorage.removeItem('appliedDiscount')
Shouldn't we remove this after the coupon deletion was a success?

2022-09-15 08:39 UTC, Gazwai commented on assets/easy_points_integration.css
> +
That's true, I'll change that

2022-09-15 08:41 UTC, Gazwai commented on assets/easy_points_integration.js
> +      sessionStorage.removeItem('appliedDiscount')
Actually  ```EasyPoints.reset({event: e});``` already does this, so I will take it out

2022-09-15 09:31 UTC, Gazwai commented on assets/easy_points_integration.js
> +  },
We needed to also submit the coupon so that the coupon is definitely taken off.  In this way, we could reset and then set the coupon. However, I have pushed another way that is similar to the ```onClickResetBtn```.

2022-10-05 23:18 UTC, NexPB requested changes

2022-10-05 23:18 UTC, NexPB commented on assets/easy_points_integration.js
> +  }, 100);
No need for timeout.

2022-10-05 23:18 UTC, NexPB commented on assets/easy_points_integration.js
> +  resetDiscount: function() {
Let's name this `removeCoupon`

2022-10-05 23:18 UTC, NexPB commented on assets/easy_points_integration.js
> +        //   .forEach(node => node.addEventListener('click', this.onClickSetCoupon));
Let's delete.

2022-10-05 23:18 UTC, NexPB commented on assets/easy_points_integration.js
> +        e.target.setAttribute('disabled', true);
Indentation is off here.

2022-10-05 23:18 UTC, NexPB commented on assets/easy_points_integration.js
> +    // }
Let's remove

2022-10-05 23:18 UTC, NexPB commented on snippets/easy_points_account_balance.liquid
> +          <span data-loyal-target="balance">{{ customer_ep_metafield.balance }}</span><span class="easy-points__text">{{ 'easypoints.points' | t }}</span>
Space needs to stay here.

2022-10-06 01:25 UTC, Gazwai commented on assets/easy_points_integration.js
> +        e.target.setAttribute('disabled', true);
I removed the checkoutBtn redefine but I couldn't find the off indentation so I just tried to make it cleaner. 

<img width="1022" alt="Screen Shot 2022-10-06 at 10 18 51" src="https://user-images.githubusercontent.com/84076465/194193143-ccf95b23-74a1-4728-892e-7101ff345173.png">

2022-10-07 05:45 UTC, NexPB approved these changes

2022-10-07 05:45 UTC, merged