Harry/asset install boilerplates
TeamLunaris/easypoints-integration-boilerplate pull request #23
Opened 2023-06-08 01:05 UTC by helording

Boilerplates from the former asset install function. Temporarily put into a new folder to separate them from existing boilerplates. This is done so problematic files are easier to locate.  

- asset_install_boilerplate/assets to be pasted in assets folder of theme
- asset_install_boilerplate/snippets to be pasted in snippets folder of theme

- asset_install_boilerplate/locales/en.txt to be pasted at the bottom of locales/en.default.json
- asset_install_boilerplate/locales/jp.txt to be pasted at the bottom of locales/ja.json line

- asset_install_boilerplate/layout/theme_inserts.txt to be pasted into specified layout/theme.liquid lines

2023-06-08 01:37 UTC, tieuu commented on asset_install_boilerplates/layout/theme_inserts.txt
> +== at line 237 ==
is the line gonna be the same every time?

2023-06-08 01:37 UTC, tieuu commented on asset_install_boilerplates/layout/theme_inserts.txt
> +  {%- comment -%} END EASYPOINTS {%- endcomment -%}
also the indentation is weird man

2023-06-08 01:37 UTC, tieuu commented on asset_install_boilerplates/locales/en.txt
is there a reason why this is not a json file and is txt instead?

2023-06-08 01:37 UTC, tieuu commented on asset_install_boilerplates/snippets/easy_points.liquid
> +          hash: "{{ customer.id | append: shop.permanent_domain | append: "d96886fc8fb45617476366d9bddfe536" | md5 }}"
iirc lorenzo said we dont need this?

2023-06-08 01:37 UTC, tieuu commented on asset_install_boilerplates/snippets/easy_points_bonus.liquid
> +  	    if point_ratio > final_point_ratio
dude the indentation is really weird

2023-06-08 01:37 UTC, tieuu commented on asset_install_boilerplates/snippets/easy_points_bonus.liquid
> +  	  endif
this one should be wrapping the smaller endif above too right?

2023-06-08 01:39 UTC, NexPB commented on asset_install_boilerplates/layout/theme_inserts.txt
> +== at line 237 ==
No lel

2023-06-08 01:40 UTC, NexPB commented on asset_install_boilerplates/locales/en.txt
Yea should be `.json`

2023-06-14 01:28 UTC, helording commented on asset_install_boilerplates/snippets/easy_points_bonus.liquid
> +  	    if point_ratio > final_point_ratio
Seems to be fixed

2023-06-14 01:28 UTC, helording commented on asset_install_boilerplates/snippets/easy_points.liquid
> +          hash: "{{ customer.id | append: shop.permanent_domain | append: "d96886fc8fb45617476366d9bddfe536" | md5 }}"
Removed

2023-06-14 01:29 UTC, helording commented on asset_install_boilerplates/snippets/easy_points_bonus.liquid
> +  	  endif
Seems to be fixed

2023-06-14 17:09 UTC, NexPB commented on templates/jp.json
Its `ja.json`and the folder is `locales/` - apply same to `en.json`

2023-06-14 17:09 UTC, NexPB commented on templates/jp.json
> +}
End line break at end of files of your files

2023-06-15 00:24 UTC, azdevc commented
> @azdevc can you make a separate pr for your intergration changes! This is not a PR meant for that.

2023-06-15 01:17 UTC, NexPB requested changes
Make sure to remove any obsolete hash core referrences.

2023-06-15 01:17 UTC, NexPB commented on snippets/easy_points.liquid
> +      <input type="hidden" id="customerHash" name="customerHash" value="{{ customer.id | append: shop.permanent_domain | append: "d96886fc8fb45617476366d9bddfe536" | md5 }}">
Still using hash.

2023-06-15 01:17 UTC, NexPB commented on assets/easy_points.js
> +    }
Code pbsolete you'll need to test if everything still works when removing.

2023-06-15 01:24 UTC, NexPB commented on templates/jp.json
As discussed with Azino in discord lets name then `ja-ep.json` in the `/locales` folder

2023-06-15 01:39 UTC, helording commented on asset_install_boilerplates/layout/theme_inserts.txt
> +  {%- comment -%} END EASYPOINTS {%- endcomment -%}
fixed

2023-06-15 01:39 UTC, helording commented on asset_install_boilerplates/layout/theme_inserts.txt
> +== at line 237 ==
Ill just include the snippets then. Also changed the file to liquid for VSCode styling. Makes it easier to read.

2023-06-15 01:39 UTC, helording commented on asset_install_boilerplates/locales/en.txt
fixed

2023-06-15 01:42 UTC, helording commented on asset_install_boilerplates/snippets/easy_points_bonus.liquid
> +  	    if point_ratio > final_point_ratio
<img width="762" alt="image" src="https://github.com/TeamLunaris/easypoints-integration-boilerplate/assets/116704220/e92d81bf-6509-445a-aacd-7388da323b42">

In my VSCode it looks like this ?_?... strange

2023-06-15 01:43 UTC, helording commented on templates/jp.json
doneskies

2023-06-15 01:44 UTC, helording commented on templates/jp.json
> +}
fixed

2023-06-15 01:47 UTC, helording commented on assets/easy_points.js
> +    }
Ok. For the meantime should we just comment it out along with hash codes so its easier to add back if needed?

2023-06-15 03:03 UTC, NexPB commented on assets/easy_points.js
> +    }
> Ok. For the meantime should we just comment it out along with hash codes so its easier to add back if needed?

Or we can check the git history if we need it after all :D

2023-06-15 03:05 UTC, NexPB commented on templates/jp.json
`-ep` stands for easyPoints I didn't typo they should remain 2 separate files.

2023-06-15 06:08 UTC, helording commented on assets/easy_points.js
> +    }
you right fam

2023-06-15 16:50 UTC, NexPB requested changes

2023-06-15 16:50 UTC, NexPB commented on locales/ja-en.json
You probably didn't see my comment in the thread but please rename to:

- `en-ep.json`
- `ja-ep.json`

2023-06-15 16:50 UTC, NexPB commented on snippets/easy_points_total_points.liquid
> +{%- comment -%} END EASYPOINTS {%- endcomment -%}
You can change your vscode settings to inserts a linebreak at the end of your files : )

2023-06-15 16:50 UTC, NexPB commented on snippets/redemption_form.liquid
We can rename these file to prepend `easy_points` while we're at it.

2023-06-15 16:50 UTC, NexPB commented on assets/easy_points.js
Has more obsolute hash references :)

2023-06-15 16:51 UTC, NexPB commented
@Gazwai once this is merged we should do the same as we did in solaris and replace the hardcoded multiplier values.

2023-06-16 01:48 UTC, Gazwai commented
> replace the hardcoded multiplier values

Made a Linear on the EP workspace
https://linear.app/easypoints/issue/COR-74/asset-boilerplate-replace-hardcoded-multiplier-values

2023-06-19 00:57 UTC, helording commented on assets/easy_points.js
I think I removed the values correctly but it might need to be doubled checked by

2023-06-19 18:10 UTC, NexPB requested changes

2023-06-19 18:10 UTC, NexPB commented on assets/easy_points.js
> -      (custId && custHash && staleSessionKey('customerMetafieldUpdatedAt', easyPointsSession)) ||
Only the `custHash` should be removed.

2023-06-19 18:10 UTC, NexPB commented on assets/easy_points.js
> +      var params = new URLSearchParams();
Seems like params is obsolete now.

2023-06-19 18:10 UTC, NexPB commented on assets/easy_points.js
> +          if (!(custId)) {
Remove extra `()` wrap

2023-06-20 22:07 UTC, NexPB approved these changes
Looks good to me now. Let's do one more integration based on this PR and then merge it in. Afterwards I'll check your Azino's PR.

2023-07-24 01:06 UTC, merged