perf: point exclusion product point display
TeamLunaris/easypoints-integration-boilerplate pull request #27
Opened 2023-09-20 01:50 UTC by azdevc

- added a fallback condition with `no-easy-points` tags for products in point exclusion collection

- show a default text that says the product is excluded from point rewards

- commented out the default CSS that targets [point-exclusion-product] to display none by default

2023-09-20 04:54 UTC, NexPB requested changes

2023-09-20 04:54 UTC, NexPB commented on snippets/easy_points_product_price_value.liquid
> +          endfor
This should not be within the collection `for` loop, this code right now will go through every tag for every collection

2023-09-20 04:54 UTC, NexPB commented on snippets/easy_points_product_points.liquid
> +{%- comment -%} END EASYPOINTS {%- endcomment -%}
Missing linebrak at the end of the file.

2023-09-20 04:54 UTC, NexPB commented on snippets/easy_points_product_points.liquid
> +    {% render 'easy_points_product_price_value', item: item, price: price %}
We should pass `worth_points` to this otherwise we're doing work twice.

2023-09-20 08:47 UTC, azdevc commented on snippets/easy_points_product_points.liquid
> +{%- comment -%} END EASYPOINTS {%- endcomment -%}
kek

2023-09-20 09:13 UTC, azdevc commented on snippets/easy_points_product_points.liquid
> +    {% render 'easy_points_product_price_value', item: item, price: price %}
done

2023-09-21 00:01 UTC, NexPB requested changes

2023-09-21 00:01 UTC, NexPB commented on snippets/easy_points_product_points.liquid
> +
Let's move this within the liquid block. so we can get rid of the `{%- -%}`

2023-09-21 00:01 UTC, NexPB commented on snippets/easy_points_product_price_value.liquid
> +    assign worth_points = worth_points
Just to be sure I would set a default: `worth_points | defualt: true`

2023-09-22 02:45 UTC, merged