Feat: easyPoints SDK integration files
TeamLunaris/easypoints-integration-boilerplate pull request #33
Opened 2024-05-28 04:35 UTC by Tw33t3r

2024-05-28 05:55 UTC, NexPB requested changes

2024-05-28 05:55 UTC, NexPB commented on assets/easy_points.js
We did not replace all of this, right? We can only delete parts here.

2024-05-28 05:55 UTC, NexPB commented on assets/easy_points_integration.js
> -  // }
Please keep this as it is used as a reference

2024-05-28 05:55 UTC, NexPB commented on assets/easy_points_integration.js
> - *
I'd like to keep this, and even bump it to v2.0

2024-05-28 05:55 UTC, NexPB commented on assets/easy_points_integration.js
> -    recalculate: function(subtotal = null) {
This is deleted but still used

2024-05-28 05:55 UTC, NexPB commented on snippets/easy_points_redemption_form.liquid
> +      {%- endif -%}
Why was this added?

2024-06-07 06:02 UTC, wjlee2020 commented
just my two cents: it'd be cool if we could update this to typescript. and let's try to make this into a private repo so assholes like me don't make comments

2024-07-18 05:28 UTC, NexPB approved these changes

2024-07-18 05:38 UTC, merged