Birthday 2
TeamLunaris/easypoints-integration-boilerplate pull request #5
Opened 2021-06-16 01:37 UTC by azdevc

2021-06-16 03:10 UTC, NexPB requested changes

2021-06-16 03:10 UTC, NexPB commented on assets/easy_points_integration.css
> +  margin-left: var(--ep-spacer-1);;
Has an extra `;`

2021-06-16 03:10 UTC, NexPB commented on assets/easy_points_integration.js
> +        .forEach(node => node.addEventListener('mousedown', this.onClickSetCoupon));
I still want it to be click by default. For edgecases we'll switch it to `mousedown` as a last resort only.

2021-06-17 06:50 UTC, azdevc commented on assets/easy_points_integration.css
> +  margin-left: var(--ep-spacer-1);;
done

2021-06-17 06:51 UTC, azdevc commented on assets/easy_points_integration.js
> +        .forEach(node => node.addEventListener('mousedown', this.onClickSetCoupon));
I put it back to click for now, implement solution later

2021-06-17 06:59 UTC, merged